# Generated by Django 3.1 on 2020-08-31 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0005_auto_20200831_0908'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='mobile_number',
        ),
        migrations.AddField(
            model_name='teacher',
            name='phone_number',
            field=models.CharField(default='2134560456', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='institution',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='institution.institute'),
        ),
    ]
