# Generated by Django 3.1 on 2020-12-16 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='profileimg',
            field=models.ImageField(default='none', upload_to='teacher-images/'),
            preserve_default=False,
        ),
    ]
