# Generated by Django 3.1 on 2020-09-02 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_auto_20200831_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='institution_email',
            field=models.EmailField(default='rcoem@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
