# Generated by Django 3.1 on 2020-09-02 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_teacher_institution_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentTeacherClassMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_email', models.EmailField(max_length=254)),
                ('student_email', models.EmailField(max_length=254)),
                ('standard', models.IntegerField()),
                ('section', models.CharField(max_length=10)),
                ('subject', models.CharField(max_length=200)),
            ],
        ),
    ]
