# Generated by Django 3.1 on 2020-09-03 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_studentteacherclassmapping'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentTeacherClassMapping',
        ),
    ]
