# Generated by Django 3.1 on 2020-09-04 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='key',
            field=models.CharField(default='Hackathon', max_length=200),
        ),
    ]
