# Generated by Django 3.1 on 2020-12-16 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_email', models.EmailField(max_length=254)),
                ('classroom_id', models.IntegerField()),
                ('conversation', models.TextField()),
                ('last_msg', models.CharField(max_length=10)),
            ],
        ),
    ]
