# Generated by Django 3.1 on 2020-09-03 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='title',
            field=models.CharField(default='Assignment 1', max_length=200),
            preserve_default=False,
        ),
    ]
