# Generated by Django 3.1 on 2020-09-04 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_assignment_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.CharField(default='04-09-2020', max_length=10),
        ),
    ]
