# Generated by Django 3.1 on 2020-09-04 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
        ('classroom', '0003_auto_20200904_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='assign_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('classroom', 'student', 'date')},
        ),
    ]
