# Generated by Django 3.1 on 2020-09-05 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0004_auto_20200904_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.CharField(default='05-09-2020', max_length=10),
        ),
    ]
