# Generated by Django 3.1 on 2020-09-27 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0005_auto_20200905_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.CharField(default='27-09-2020', max_length=10),
        ),
    ]
