# Generated by Django 3.1 on 2020-09-03 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(max_length=200, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact_person', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=10)),
                ('website', models.URLField(blank=True)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
