# Generated by Django 3.0.8 on 2020-08-28 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institute',
            name='password',
        ),
    ]
