# Generated by Django 3.0.8 on 2020-08-28 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0002_remove_institute_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
