# Generated by Django 3.1 on 2020-08-28 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0003_auto_20200828_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='institution_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
